#!/usr/bin/env -S python3 -u
import argparse, socket, time, json, select, struct, sys, math

class Router:
    # keeps information about AS neighbors
    relations = {}
    sockets = {}
    ports = {}

    # initializes our BGP router
    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        self.forwarding_table = []
        self.withdraws = []
        self.updates = []

        # update the neighbors information for each connection, and send handshake
        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            self.send(neighbor, json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}  }))

    # takes a destination ip and produces an identical source ip, except the last octet is 1 to represent our router
    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    # takes an ip and converts it to an integer
    def ip_to_int(self, ip):
        quads = list(int(qdn) for qdn in ip.split('.'))
        
        # add the integers together with appropriate bit shift
        return (quads[0] << 24) + (quads[1] << 16) + (quads[2] << 8) + quads[3]
    
    # takes an integer and converts it to an ip
    def int_to_ip(self, n):
      quads = []
      
      # uses repeating % 256 to find ip quads in reverse order
      for i in range(4):
        quads.insert(0, str(n % 256))
        n >>= 8
      return ".".join(quads)


    # sends a specified message to a given AS neighbor
    def send(self, network, message):
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    # actively receives messages from neighbor AS's
    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]

            # for each socket, listen for messages
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break

                msg = json.loads(k.decode('utf-8'))

                self.process_message(srcif, msg)

                print("Received message '%s' from %s" % (msg, srcif))
        return


    # decides which neighbors to contact based off of our relationship with the sender and our neighbors
    def contact_neighbors(self, sender, announcement, msg_type="update"):
      # rules:
      # - 1) Update received from a customer: send updates to all other neighbors
      # - 2) Update received from a peer or a provider: only send updates to your customers

      # for every neighbor
      for neighbor in self.relations:

        # don't send the sender the info they sent us
        if (neighbor == sender):
          continue

        # for every neighbor, send them the update IF they are:
        # - either a customer (rule 2 - customer gets all info)
        # - or the sender is a customer (rule 1 - all customer updates get sent to everyone)

        if ((self.relations[sender] == "cust") or (self.relations[neighbor] == "cust")):
          self.send(neighbor, json.dumps({"type": msg_type, "src": self.our_addr(neighbor), "dst": neighbor, "msg": announcement }))


    # decides which functions to call based on the message
    def process_message(self, sender, msg):
      if msg['type'] == "update":
        return self.handle_updating(sender, msg)

      elif msg['type'] == "data":
        return self.handle_data(sender, msg)

      elif msg['type'] == "withdraw":
        return self.handle_withdraw(sender, msg)

      elif msg['type'] == "dump":
        return self.handle_dump(sender)


    # handles updating forwarding table based on recieved information
    def handle_updating(self, sender, msg):

      # create a forwarding table row from the message contents (this holds private info)
      private_announcement = {
          "origin": msg["msg"]["origin"],
          "localpref": msg["msg"]["localpref"],
          "network": msg["msg"]["network"],
          "ASPath": msg["msg"]["ASPath"],
          "netmask": msg["msg"]["netmask"],
          "selfOrigin": msg["msg"]["selfOrigin"],
          "peer": sender
      }

      # add the row to the existing table
      self.forwarding_table.append(private_announcement)

      # this is the public version of the private update - with private information removed (and our router added to the path)
      public_announcement = {
          "network": msg["msg"]["network"],
          "netmask": msg["msg"]["netmask"],
          "ASPath": [self.asn] + msg["msg"]["ASPath"],
      }

      # decide who to share this with
      self.contact_neighbors(sender, public_announcement)

      # store the updates (incase of disaggregation later)
      self.updates.append(private_announcement)

      # handle aggregation
      self.handle_aggregation()
    
    # sends our forwarding table to the sender
    def handle_dump(self, sender):
      self.send(sender, json.dumps({"type": "table", "src": self.our_addr(sender), "dst": sender, "msg": self.forwarding_table }))

    # handles forwarding of data messages to neighbors based on forwarding table
    def handle_data(self, sender, msg):

      best_match = None
      best_netmask = -1

      # for every possible route in our forwarding table
      for possible in self.forwarding_table:
        network = self.ip_to_int(possible["network"])
        netmask = self.ip_to_int(possible["netmask"])
        destination = self.ip_to_int(msg["dst"])

        # if the destination is is this network
        if ((destination & netmask) == (network & netmask)):
          # save the best match
          # rules:
          # 1) The entry with the longest (most specific) netmask wins. If netmasks are equal...
          # 2) The entry with the highest localpref wins. If the localprefs are equal…
          # 3) The entry with selfOrigin as true wins. If all selfOrigins are the equal…
          # 4) The entry with the shortest ASPath wins. If multiple entries have the shortest length…
          # 5) The entry with the best origin wins, where IGP > EGP > UNK. If multiple entries have the best origin…
          # 6) The entry from the neighbor router (i.e., the src of the update message) with the lowest IP address.

          # rule 1
          if (best_netmask < netmask):
            best_netmask = netmask
            best_match = possible

          elif (best_netmask == netmask):
            # rule 2
            if (best_match["localpref"] < possible["localpref"]):
              best_netmask = netmask
              best_match = possible
            elif (best_match["localpref"] == possible["localpref"]):
              # rule 3
              if (best_match["selfOrigin"] < possible["selfOrigin"]):
                best_netmask = netmask
                best_match = possible
                
              elif (best_match["selfOrigin"] == possible["selfOrigin"]):
                # rule 4
                if (len(best_match["ASPath"]) > len(possible["ASPath"])):
                  best_netmask = netmask
                  best_match = possible
                
                elif (len(best_match["ASPath"]) == len(possible["ASPath"])):
                  # rule 5
                  origin_ranks = {"IGP": 3, "EGP": 2, "UNK": 1}

                  if (origin_ranks[best_match["origin"]] < origin_ranks[possible["origin"]]):
                    best_netmask = netmask
                    best_match = possible

                  elif (origin_ranks[best_match["origin"]] == origin_ranks[possible["origin"]]):
                    # rule 6
                    if (self.ip_to_int(best_match["peer"]) > self.ip_to_int(possible["peer"])):
                      best_netmask = netmask
                      best_match = possible
      
      # if a best path exists forward the message, otherwise send no route message to sender
      # only forward the message of the source or destination is a customer
      if (best_match):
        src_relationship = self.relations[sender]
        dst_relationship = self.relations[best_match["peer"]]

        if (src_relationship == "cust" or dst_relationship == "cust"):
          self.send(best_match["peer"], json.dumps(msg))
          return
      
      self.send(sender, json.dumps({"type": "no route", "src": self.our_addr(sender), "dst": sender, "msg": {} }))

    
    # handles withdraws by saving them, updating forwarding table, and notifying appropriate neighbors
    def handle_withdraw(self, sender, msg):
      # cache withdraw
      self.withdraws.append(msg)

      # update forwarding table:
      # create a new forwarding table (throw out the old one)
      self.forwarding_table = []

      # loop through updates list:
      # and for each route in our updates list that matches any route mentioned in the withdraws list, do not include it in our new forwarding table
      for update in self.updates:
        withdrawn = False
        
        for withdraw in self.withdraws:
          for network in withdraw["msg"]:

            # if the route matches the withdrawn route, mark not to include it
            if (update["peer"] == withdraw["src"] and
                update["network"] == network["network"] and
                update["netmask"] == network["netmask"]):
              withdrawn = True
        
        # if the route in our updates list doesn't match a route in the with draw, add it to the new table (keep it)
        if not withdrawn:
          self.forwarding_table.append(update)

      # update appropriate neighbors
      self.contact_neighbors(sender, msg["msg"], "withdraw")

      # handle aggregation of the new forwarding table
      self.handle_aggregation()



    # handles aggregating appropropriate forwarding table entries
    def handle_aggregation(self):
      # aggregation rules:
      # if there are two or more entries in the forwarding table aggregate if:
      # 1) they are adjacent numerically
      # 2) forward to the same next-hop router
      # 3) have the same attributes (e.g., localpref, origin, etc.)

      # create a new forwarding table (save the old one)
      old_forwarding_table = list(self.forwarding_table)
      self.forwarding_table = []

      # loop through our old forwarding table:
      # for each old route, check if it can be aggregated with any of the other routes
      for route in old_forwarding_table:

        # include everything for comparison except network and netmask
        entry = {
            "peer": route["peer"],
            "localpref" : route["localpref"],
            "origin" : route["origin"],
            "selfOrigin" : route["selfOrigin"],
            "ASPath" : route["ASPath"]
        }
        
        network = self.ip_to_int(route["network"])
        netmask = self.ip_to_int(route["netmask"])


        for possible_route in old_forwarding_table:
          # skip if we're comparing to same route
          if (route == possible_route):
            continue
          
          possible_network = self.ip_to_int(possible_route["network"])
          possible_netmask = self.ip_to_int(possible_route["netmask"])
          
          # include everything for comparison except network and netmask
          possible_entry = {
            "peer": possible_route["peer"],
            "localpref" : possible_route["localpref"],
            "origin" : possible_route["origin"],
            "selfOrigin" : possible_route["selfOrigin"],
            "ASPath" : possible_route["ASPath"]
          }
          
          # rules 2 (peer/next hop matches) and 3 (attributes match)
          if (entry == possible_entry):
            # rule 1 check for adjacent IPs:
            # netmasks need to be the same and last digit after netmask needs to be different
            if (netmask == possible_netmask):
              # exclusive or to find differing bits between the networks
              difference = network ^ possible_network

              # find the first bit after the netmask:
              # flip all the netmask bits (keep size of 8.8.8.8)
              # then add 1 to get the value of the boundary bit
              
              # example: netmask: 255.255.255.0
              # flip netmask bits: 0.0.0.255 --> 0.0.0.11111111
              # add 1: 0.0.1.00000000 --> 256
              
              inverted = ~netmask & 0xFFFFFFFF
              lowest_bit = inverted + 1
              
              # make sure the only difference is the bit after the netmask
              if (difference == lowest_bit):
                # aggregate:
                aggregated = possible_entry # keep the attributes that are identical across the networks
                
                # shorten the netmask by 1 bit
                aggregated["netmask"] = self.int_to_ip(netmask - lowest_bit)

                # make the aggregated network the smaller of the 2 networks
                aggregated["network"] = self.int_to_ip(min(network, possible_network))
                
                # remove the 2 old routes
                old_forwarding_table.remove(route)
                old_forwarding_table.remove(possible_route)

                # add the new aggregated entry
                old_forwarding_table.append(aggregated)
                
                # update forwarding table
                self.forwarding_table = list(old_forwarding_table)
                
                # call recursively everytime we aggregate (aggregation on top of aggregation might be possible)
                return self.handle_aggregation()
        
        
        # if no aggregation is possible, keep the current route
        self.forwarding_table.append(route)


# command line parser, used to create the router
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
