#!/usr/bin/env python3

import json
import socket
import sys
import ssl

#constants for defaults
DEFAULT_PORT = 27993
DEFAULT_SECURE_PORT = 27994

#takes a message from server, returns error if it doesn't match its type, otherwise returns the message
def validate_server_msg(msg):
  #checks and verifies that a message of given type has its required contents, if not, error
  try:
    msg_type = msg["type"]
    if (msg_type == "start"):
      if ("id" not in msg):
        raise Exception(f"Server sent {msg_type} message, but did not send expected contents")
    elif (msg_type == "retry"):
      if ("id" not in msg or "guesses" not in msg):
        raise Exception(f"Server sent {msg_type} message, but did not send expected contents")
    elif (msg_type == "bye"):
      if ("id" not in msg or "flag" not in msg):
        raise Exception(f"Server sent {msg_type} message, but did not send expected contents")
    elif (msg_type == "error"):
      raise Exception("Server error")
    else:
      raise Exception("Server did not send a message with the expected type")
  
  except KeyError:
    raise Exception("Server did not send an expected message")
  
  #if there were no issues, return the message
  return msg


#takes a message and client, returns the servers response
def message_server(msg, client):
  #encode and send the message to the server
  client.send(msg.encode("utf-8"))

  data = b""
  
  #make sure we're collecting the entire packet - read till line break
  while b"\n" not in data:
    chunk = client.recv(4096)
    if chunk == b"":
      break
    data += chunk

  #receive message from the server and decoding
  handshake_returned = data.decode("utf-8").strip()
  
  #returning the recieved message, errors if not a valid Json
  # - sends to validation checker to further verify before returning
  try:
    return validate_server_msg(json.loads(handshake_returned))
  except json.JSONDecodeError:
    raise ValueError("Invalid JSON received from server")


#takes a port, wheather to make a secure or not secure connection, host to connect to, and user to connect.
#returns the flag recieved after guessing the correct word
def find_word(port, secure, hostname, username):
  #get all the possible words to be tested from the file and put into a list
  wordsFile = open("project1-words.txt")
  words = wordsFile.readlines()
  wordsFile.close()

  # create a socket object
  client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

  #if the connection is supposed to be secure, create secure connection
  if (secure):
    context = ssl.create_default_context()
    client = context.wrap_socket(client, server_hostname=hostname)

  # establish connection with server
  client.connect((hostname, port))

  #send the inital message to the server to start the game
  handshake_initiate = json.dumps({"type": "hello", "northeastern_username": username}) + "\n"
  response = message_server(handshake_initiate, client)


  connection_id = response["id"]

  known_letters = [] #list representing letters we know are in the word
  known_positions = {} #dictionary representing letters we know are in the word at a specific location

  #goes through all the words
  #  - if the possible guess does not match what we know is required skip it.
  #    - needs to have all the letters we know the word has
  #    - needs to have all the letters in the correct position as the word
  for i in range(len(words)):
    word = words[i].strip()
    skip_word = False

    #if the word does not match with what we know, move on past this word - dont even guess it
    for letter in known_letters:
      if (not letter in word):
        skip_word = True
        break

    if (skip_word):
      continue

    #if the word does not match with what we know, move on past this word - dont even guess it
    for key, value in known_positions.items():
      if (not word[key] == value):
        skip_word = True
        break

    #if i breaks skip this word (dont guess it)
    if (skip_word):
      continue

    #if the word meets all the requirements, submit it as a guess to the server in the correct format
    guess_shake = json.dumps({"type": "guess", "id": connection_id, "word": word}) + "\n"
    response = message_server(guess_shake, client)

    #if the server returns the completion message, return the flag
    if (response["type"] == "bye"):
      print(response["flag"])
      break

    marks = response["guesses"][-1]["marks"]

    #for each "mark" the server returns, if it gives us info about the word that we
    #don't already know, document it
    for x in range(len(marks)):
      if (marks[x] == 1):
        if (not word[x] in known_letters):
          known_letters.append(word[x])
      elif (marks[x] == 2):
        known_positions[x] = word[x]
  
  #close the client
  client.close()


def main():

  #verifies that at least the 2 required arguments after the name are provided
  if len(sys.argv) < 3:
    raise Exception("You have too little arguments")

  #set hostname and username to the 2 last arguements
  username = sys.argv[-1]
  hostname = sys.argv[-2]
    
  #if only the 2 required arguements are present
  if len(sys.argv) == 3:
    find_word(DEFAULT_PORT, False, hostname, username)
    
  #if only the -s flag and 2 required arguements are present
  elif len(sys.argv) == 4:
    find_word(DEFAULT_SECURE_PORT, True, hostname, username)

  #if only the -p flag and port and 2 required arguements are present
  elif len(sys.argv) == 5:
    port = int(sys.argv[2])
    find_word(port, False, hostname, username)
    
  #if all the -p, port, -s, and 2 required arguements are present
  elif len(sys.argv) == 6:
    port = int(sys.argv[2])
    find_word(port, True, hostname, username)
    
  #have too many arguements
  else:
    raise Exception("You have too many arguments")


if __name__ == "__main__":
    main()
